"""add_google_tokens

Revision ID: 3d17260159a4
Revises: 3a168e5ca182
Create Date: 2025-03-24 09:41:26.808168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d17260159a4'
down_revision = '3a168e5ca182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('google_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('google_refresh_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'google_refresh_token')
    op.drop_column('users', 'google_token')
    # ### end Alembic commands ###
