"""add_google_tokens

Revision ID: 6337d3f516c0
Revises: 3d17260159a4
Create Date: 2025-03-24 10:22:30.456131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6337d3f516c0'
down_revision = '3d17260159a4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
